name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .  # Install the package in development mode
        
    - name: Download model
      run: python scripts/download_model.py
      env:
        MODEL_URL: ${{ secrets.MODEL_URL }}
        
    - name: Run tests
      run: |
        python -m pytest tests/
        
    # Temporarily disabled report generation
    # - name: Generate model report
    #   run: python generate_report.py
    #   
    # - name: Upload model report
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: model_report
    #     path: model_report.md
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/car-price-backend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/car-price-backend:latest
        
    - name: Start backend server
      run: |
        python backend/backend.py &
        sleep 10  # Wait for the server to start
        curl -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{"year": 2015, "make": "Toyota", "model": "Camry", "trim": "LE", "body": "sedan", "transmission": "automatic", "vin": "4T1BF1FKXEU123456", "state": "CA", "condition": 4, "odometer": 50000, "color": "blue", "interior": "black", "seller": "test", "saledate": "Mon Mar 15 2021 12:00:00"}' 